language: go
dist: trusty
sudo: false

go:
 - 1.9
 - 1.10
 - 1.11

env:
 global:
  - GO111MODULE=on
matrix:
 - TARGET=x86
 - TARGET=x64

matrix:
 fast_finish: true
 allow_failures:
  - go: tip

before_install:
 - go mod vendor

script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
 - bash <(curl -s https://codecov.io/bash)
