language: go
go:
- 1.11
- 1.12

os:
  - linux
  - windows

env:
  global:
    - GO111MODULE=on
    - GOMODULE=on

matrix:
  include:
  - go: 1.12
    env: GO111MODULE=on
  - go: 1.12
    env: GO111MODULE=off
  allow_failures:
  - go: 1.11
    env: GO111MODULE=on
  - go: 1.11
    env: GO111MODULE=off

before_install:
 - go mod download

script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
 - bash <(curl -s https://codecov.io/bash)
