language: go
dist: trusty
sudo: false

go:
 - 1.10.1
 - 1.11.4

env:
 global:
  - GO111MODULE=on

before_install:
 - go mod vendor

script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
 - bash <(curl -s https://codecov.io/bash)
