language: go
go:
- 1.11
- 1.12

os:
  - linux
  - windows

env:
  global:
    - GO111MODULE=on
    - GOMODULE=on

before_install:
 - go mod download

script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
 - bash <(curl -s https://codecov.io/bash)
